import { Destination, Food, HeritageMusic, TraditionalMedicine, TeaExperience, Phrase, TravelEssential, Festival, Translation, HikingSpot, Transport } from './types.ts';

export const SUPABASE_KEY = 'sb_publishable_c8wPY71QFNsFJKcAEuD86w_pcqen0nv';

export const UI_STRINGS: Translation = {
  heroTitle: { EN: "Discover True Beauty of Sri Lanka", SI: "ශ්‍රී ලංකාවේ සැබෑ සුන්දරත්වය සොයා ගන්න" },
  exploreDestinations: { EN: "Explore Destinations", SI: "ගමනාන්ත ගවේෂණය කරන්න" },
  popularHighlightsTitle: { EN: "The Crown Jewels of Lanka", SI: "ලංකාවේ අභිමානවත් ස්ථාන" },
  popularHighlightsSubtitle: { EN: "Journey through the three most iconic landmarks that define our island's spirit.", SI: "අපගේ දිවයිනේ ජීවය නිරූපණය කරන සුවිශේෂී ස්ථාන තුනක් හරහා සංචාරය කරන්න." },
  planYourTrip: { EN: "Plan Your Trip", SI: "සංචාරය සැලසුම් කරන්න" },
  ancientHighlights: { EN: "Ancient Sri Lanka Highlights", SI: "පැරණි ශ්‍රී ලංකාවේ විශේෂිත ස්ථාන" },
  natureAdventure: { EN: "Nature & Adventure", SI: "සොබාදහම සහ වික්‍රමය" },
  travelMemories: { EN: "Travel Memories", SI: "සංචාරක මතකයන්" },
  lankaGuideTitle: { EN: "Lanka Guide AI", SI: "ලංකා ගයිඩ් AI" },
  searchPlaceholder: { EN: "Search destinations...", SI: "ගමනාන්ත සොයන්න..." },
  filterRegionLabel: { EN: "Filter by Region", SI: "කලාපය අනුව පෙරන්න" },
  allRegions: { EN: "All Regions", SI: "සියලුම කලාප" },
  historyLabel: { EN: "The Legend & History", SI: "පුරාවෘත්තය සහ ඉතිහාසය" },
  bestTimeLabel: { EN: "Best Time to Visit", SI: "සංචාරය කිරීමට හොඳම කාලය" },
  tipsLabel: { EN: "Traveler's Wisdom", SI: "සංචාරක උපදෙස්" },
  close: { EN: "Close", SI: "වසා දමන්න" },
  exploreInterests: { EN: "Explore Your Interests", SI: "ඔබේ රුචිකත්වයන් ගවේෂණය කරන්න" }
};

export const TRANSPORT_DATA: Transport[] = [
  {
    id: 't1',
    name: { EN: 'Elite Chauffeur Service', SI: 'ප්‍රභූ රියදුරු සේවාව' },
    type: 'road',
    price: 85,
    description: { EN: 'Luxury air-conditioned sedans with English-speaking heritage guides.', SI: 'ඉංග්‍රීසි කතා කරන මගපෙන්වන්නන් සහිත සුඛෝපභෝගී රථ සේවාව.' },
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80',
    features: { EN: ['Wi-Fi Enabled', 'Refreshments Included', 'Flexible Itinerary'], SI: ['Wi-Fi පහසුකම්', 'කෙටි ආහාර', 'නම්යශීලී ගමන් මග'] }
  },
  {
    id: 't2',
    name: { EN: 'Cinnamon Air Domestic', SI: 'සිනමන් එයාර් දේශීය ගුවන්' },
    type: 'air',
    price: 240,
    description: { EN: 'Fastest link between the coast and the cultural triangle.', SI: 'මුහුදු වෙරළ සහ සංස්කෘතික ත්‍රිකෝණය අතර වේගවත්ම සබඳතාවය.' },
    image: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=800&q=80',
    features: { EN: ['Scenic Views', '30 Min Flight Time', 'Premium Lounge'], SI: ['අලංකාර දසුන්', 'විනාඩි 30ක ගමන් කාලය', 'ප්‍රභූ විවේකාගාරය'] }
  },
  {
    id: 't3',
    name: { EN: 'Viceroy Special Train', SI: 'වයිස්රෝයි විශේෂ දුම්රිය' },
    type: 'rail',
    price: 120,
    description: { EN: 'A vintage steam engine journey through the misty tea hills.', SI: 'මීදුමෙන් වැසුණු කඳුකරය හරහා යන පැරණි වාෂ්ප එන්ජින් දුම්රිය චාරිකාව.' },
    image: 'https://images.unsplash.com/photo-1474487056217-76fead63c19e?auto=format&fit=crop&w=800&q=80',
    features: { EN: ['Observation Car', 'Fine Dining', 'Heritage Decor'], SI: ['නිරීක්ෂණ මැදිරිය', 'රසවත් ආහාර', 'පෞරාණික සැරසිලි'] }
  }
];

export const DESTINATIONS: Destination[] = [
  { id: "sigiriya", name: { EN: "Sigiriya Lion Rock", SI: "සීගිරිය සිංහගිරිය" }, category: "ancient", image: "https://images.unsplash.com/photo-1580794749460-76f97b7180d8?auto=format&fit=crop&w=1920&q=80", gallery: ["https://images.unsplash.com/photo-1620054604245-566083771259?auto=format&fit=crop&w=1200&q=80"], videoUrl: "https://www.youtube.com/shorts/j4ln2UNOnZk", history: { EN: "Sigiriya, the 'Lion Rock', is a UNESCO World Heritage site and a masterpiece of ancient urban planning.", SI: "සීගිරිය හෙවත් 'සිංහගිරිය' යනු පැරණි නගර නිර්මාණකරණයේ විශිෂ්ටතම යුනෙස්කෝ ලෝක උරුමයකි." }, shortStory: { EN: "The 8th Wonder of the World – A fortress in the sky.", SI: "ලොව අටවන පුදුමය - අහස උසට විහිදුණු බලකොටුවකි." }, bestTime: { EN: "December to April", SI: "දෙසැම්බර් සිට අප්‍රේල් දක්වා" }, tips: [{ EN: "Climb early morning to avoid the heat.", SI: "රස්නය මග හැරීමට උදෑසන කාලයේ නැගීම ආරම්භ කරන්න." }], location: "Matale" },
  { id: "polonnaruwa", name: { EN: "Ancient City of Polonnaruwa", SI: "පොළොන්නරුව පැරණි නගරය" }, category: "ancient", image: "https://images.unsplash.com/photo-1656339952847-a360aee9273b?auto=format&fit=crop&w=1200&q=80", gallery: ["https://images.unsplash.com/photo-1656339952847-a360aee9273b?auto=format&fit=crop&w=1200&q=80"], history: { EN: "The second most ancient kingdom of Sri Lanka, known for its incredible stone sculptures.", SI: "ශ්‍රී ලංකාවේ දෙවන පැරණිතම රාජධානිය වන පොළොන්නරුව, විස්මිත ගල් කැටයම් සඳහා ප්‍රසිද්ධය." }, shortStory: { EN: "Where stone tells the story of an empire.", SI: "ගල් කැටයම් අධිරාජ්‍යයක කතාව පවසන තැන." }, bestTime: { EN: "July to September", SI: "ජූලි සිට සැප්තැම්බර් දක්වා" }, tips: [{ EN: "Rent a bicycle to explore the ruins.", SI: "නටබුන් නැරඹීමට බයිසිකලයක් කුලියට ගන්න." }], location: "Polonnaruwa" },
  { id: "ella", name: { EN: "Nine Arch Bridge", SI: "ආරුක්කු නවය පාලම" }, category: "mountains", image: "https://images.unsplash.com/photo-1578519050142-afb511e518de?auto=format&fit=crop&w=1200&q=80", gallery: ["https://images.unsplash.com/photo-1578519050142-afb511e518de?auto=format&fit=crop&w=1200&q=80"], history: { EN: "A colonial-era masterpiece built entirely out of rock, bricks, and cement.", SI: "ගල්, ගඩොල් සහ සිමෙන්ති වලින් පමණක් නිමවා ඇති යටත් විජිත යුගයේ අගනා නිර්මාණයකි." }, shortStory: { EN: "The bridge in the sky where time slows down.", SI: "කාලය සෙමින් ගෙවෙන අහස උසට බැඳි පාලම." }, bestTime: { EN: "January to March", SI: "ජනවාරි සිට මාර්තු දක්වා" }, tips: [{ EN: "Check the train schedule for photos.", SI: "ඡායාරූප ගැනීමට දුම්රිය කාලසටහන පරීක්ෂා කරන්න." }], location: "Badulla" },
  { id: "anuradhapura", name: { EN: "Sacred Anuradhapura", SI: "අනුරාධපුර පූජනීය නගරය" }, category: "ancient", image: "https://images.unsplash.com/photo-1621393614326-2f9ed389ce02?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "The first capital of Sri Lanka, home to the sacred Jaya Sri Maha Bodhi tree.", SI: "ශ්‍රී ලංකාවේ ප්‍රථම අගනුවර සහ ජය ශ්‍රී මහා බෝධීන් වහන්සේ වැඩසිටින පින්බිමයි." }, shortStory: { EN: "The cradle of Buddhist civilization.", SI: "බෞද්ධ ශිෂ්ටාචාරයේ තොටිල්ල." }, bestTime: { EN: "May to June", SI: "මැයි සිට ජූනි දක්වා" }, tips: [{ EN: "Dress in white for temple visits.", SI: "විහාරස්ථාන වැඳපුදා ගැනීමට සුදු ඇඳුමෙන් සැරසෙන්න." }], location: "Anuradhapura" },
  { id: "kandy-temple", name: { EN: "Temple of the Tooth", SI: "ශ්‍රී දළදා මාළිගාව" }, category: "ancient", image: "https://images.unsplash.com/photo-1665849050332-8d5d7e59afb6?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "The sacred temple housing the relic of the tooth of the Buddha.", SI: "බුදුරජාණන් වහන්සේගේ දන්ත ධාතූන් වහන්සේ වැඩසිටින පූජනීය මන්දිරයයි." }, shortStory: { EN: "The spiritual heart of the hill capital.", SI: "කඳුකර අගනුවර ආත්මික හදවත." }, bestTime: { EN: "July to August", SI: "ජූලි සිට අගෝස්තු දක්වා" }, tips: [{ EN: "Visit during evening pooja ceremonies.", SI: "සවස පූජා අවස්ථාවන්හිදී නැරඹීමට යන්න." }], location: "Kandy" },
  { id: "galle-fort", name: { EN: "Galle Dutch Fort", SI: "ගාල්ල ලන්දේසි කොටුව" }, category: "ancient", image: "https://images.unsplash.com/photo-1654561773591-57b9413c45c0?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A historical fortification built by the Portuguese and extensively fortified by the Dutch.", SI: "පෘතුගීසීන් විසින් ඉදිකළ පසුව ලන්දේසීන් විසින් ශක්තිමත් කරන ලද ඓතිහාසික බලකොටුවකි." }, shortStory: { EN: "Where colonial charm meets the Indian Ocean.", SI: "යටත් විජිත අලංකාරය ඉන්දියන් සාගරය හමුවන තැන." }, bestTime: { EN: "November to April", SI: "නොවැම්බර් සිට අප්‍රේල් දක්වා" }, tips: [{ EN: "Walk the ramparts at sunset.", SI: "හිරු බැස යන විට කොටු පවුර මත ඇවිද යන්න." }], location: "Galle" },
  { id: "dambulla", name: { EN: "Dambulla Cave Temple", SI: "දඹුල්ල රන්ගිරි රජමහා විහාරය" }, category: "ancient", image: "https://images.unsplash.com/photo-1546271876-af6caec5fae5?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "The largest and best-preserved cave temple complex in Sri Lanka.", SI: "ශ්‍රී ලංකාවේ විශාලතම සහ හොඳින්ම සුරැකිව ඇති ලෙන් විහාර සංකීර්ණයයි." }, shortStory: { EN: "Ancient murals painted within living stone.", SI: "ජීවමාන ගල් ගුහා තුළ ඇඳි පැරණි සිතුවම්." }, bestTime: { EN: "Year-round", SI: "වසර පුරා" }, tips: [{ EN: "Be prepared for hundreds of steps.", SI: "පඩිපෙළ සිය ගණනක් නැගීමට සූදානම් වන්න." }], location: "Matale" },
  { id: "mirissa", name: { EN: "Mirissa Beach", SI: "මිරිස්ස වෙරළ" }, category: "beach", image: "https://images.unsplash.com/photo-1544921603-91185f0962b1?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A crescent-shaped beach known for whale watching and surf culture.", SI: "තල්මසුන් නැරඹීම සහ සර්ෆින් සඳහා ප්‍රසිද්ධ අඩ සඳක හැඩැති වෙරළ තීරයකි." }, shortStory: { EN: "Sun-kissed shores and oceanic giants.", SI: "හිරු රැසින් නැහැවුණු වෙරළ සහ සාගර දැවැන්තයින්." }, bestTime: { EN: "November to March", SI: "නොවැම්බර් සිට මාර්තු දක්වා" }, tips: [{ EN: "Visit Coconut Tree Hill for photos.", SI: "ඡායාරූප ගැනීමට කොකනට් ට්‍රී හිල් වෙත යන්න." }], location: "Matara" },
  { id: "unawatuna", name: { EN: "Unawatuna Bay", SI: "උණවටුන බොක්ක" }, category: "beach", image: "https://images.unsplash.com/photo-1558446791-ac5fec3caddf?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A famous bay known for its turquoise waters and coral reefs.", SI: "එහි නිල්වන් ජලය සහ කොරල් පර සඳහා ප්‍රසිද්ධ සුන්දර වෙරළ තීරයකි." }, shortStory: { EN: "A tropical haven for swimmers and divers.", SI: "කිමිදුම්කරුවන් සඳහා වූ නිවර්තන පාරාදීසයකි." }, bestTime: { EN: "December to April", SI: "දෙසැම්බර් සිට අප්‍රේල් දක්වා" }, tips: [{ EN: "Try snorkeling at Jungle Beach nearby.", SI: "අසල ඇති ජංගල් බීච් හි ස්නෝකර්ලින් උත්සාහ කරන්න." }], location: "Galle" },
  { id: "arugambay", name: { EN: "Arugam Bay", SI: "ආරුගම්බේ" }, category: "beach", image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A world-renowned surf spot on the East Coast.", SI: "නැගෙනහිර වෙරළ තීරයේ ලොව සුප්‍රසිද්ධ සර්ෆින් ක්‍රීඩා මධ්‍යස්ථානයකි." }, shortStory: { EN: "The surf capital of the island.", SI: "දිවයිනේ සර්ෆින් අගනුවර." }, bestTime: { EN: "April to October", SI: "අප්‍රේල් සිට ඔක්තෝබර් දක්වා" }, tips: [{ EN: "Rent a scooter to find secluded spots.", SI: "නිස්කලංක ස්ථාන සොයා ගැනීමට ස්කූටරයක් කුලියට ගන්න." }], location: "Ampara" },
  { id: "nilaveli", name: { EN: "Nilaveli Beach", SI: "නිලාවේලි වෙරළ" }, category: "beach", image: "https://images.unsplash.com/photo-1544921603-91185f0962b1?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "Pure white sands and Pigeon Island snorkeling.", SI: "පිරිසිදු සුදු වැලි සහ පරෙවි දූපතේ ස්නෝකර්ලින් අත්දැකීම." }, shortStory: { EN: "The pristine jewel of Trincomalee.", SI: "ත්‍රිකුණාමලයේ පිරිසිදු සුන්දරත්වය." }, bestTime: { EN: "May to September", SI: "මැයි සිට සැප්තැම්බර් දක්වා" }, tips: [{ EN: "Take a boat to Pigeon Island early.", SI: "උදෑසනම පරෙවි දූපතට බෝට්ටුවකින් යන්න." }], location: "Trincomalee" },
  { id: "yala", name: { EN: "Yala National Park", SI: "යාල ජාතික උද්‍යානය" }, category: "wildlife", image: "https://images.unsplash.com/photo-1590766940554-634a7ed41450?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "The most visited park in Lanka, home to the elusive leopard.", SI: "ලංකාවේ වැඩිම පිරිසක් නරඹන, දිවියන් සඳහා ප්‍රසිද්ධ උද්‍යානයයි." }, shortStory: { EN: "The realm of the Sri Lankan leopard.", SI: "ශ්‍රී ලාංකීය දිවියාගේ අඩවිය." }, bestTime: { EN: "February to June", SI: "පෙබරවාරි සිට ජූනි දක්වා" }, tips: [{ EN: "Book a morning safari for best sightings.", SI: "සතුන් නැරඹීමට උදෑසන සවාරියක් වෙන්කර ගන්න." }], location: "Hambantota" },
  { id: "udawalawe", name: { EN: "Udawalawe National Park", SI: "උඩවලව ජාතික උද්‍යානය" }, category: "wildlife", image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "Famous for its large population of wild Asian elephants.", SI: "විශාල වන අලි ගහනයක් සඳහා ප්‍රසිද්ධ ජාතික උද්‍යානයකි." }, shortStory: { EN: "Where elephants roam free.", SI: "අලි ඇතුන් නිදහසේ සැරිසරන බිම." }, bestTime: { EN: "Year-round", SI: "වසර පුරා" }, tips: [{ EN: "Visit the Elephant Transit Home nearby.", SI: "අසල ඇති අලි අනාථාගාරය නැරඹීමට යන්න." }], location: "Ratnapura" },
  { id: "horton-plains", name: { EN: "Horton Plains", SI: "හෝර්ටන් තැන්න" }, category: "mountains", image: "https://images.unsplash.com/photo-1671432751719-d1a032c1a369?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A cold, windy plateau featuring World's End precipice.", SI: "ලෝකාන්තය පිහිටි සීතල, සුළං සහිත උස් තැන්නකි." }, shortStory: { EN: "A trek to the edge of the world.", SI: "ලෝකයේ කෙළවරට යන පියමං ගමනක්." }, bestTime: { EN: "January to March", SI: "ජනවාරි සිට මාර්තු දක්වා" }, tips: [{ EN: "Arrive before 9 AM for clear views.", SI: "පැහැදිලි දර්ශන සඳහා උදේ 9 ට පෙර පැමිණෙන්න." }], location: "Nuwara Eliya" },
  { id: "adams-peak", name: { EN: "Adam's Peak", SI: "ශ්‍රී පාදය" }, category: "mountains", image: "https://images.unsplash.com/photo-1705730312722-095ca8123d48?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A sacred mountain with a footprint at the summit.", SI: "මුදුනේ සිරිපතුල පිහිටි පූජනීය කඳු මුදුනකි." }, shortStory: { EN: "The ultimate spiritual ascent.", SI: "ඉහළම ආධ්‍යාත්මික තරණය." }, bestTime: { EN: "December to April", SI: "දෙසැම්බර් සිට අප්‍රේල් දක්වා" }, tips: [{ EN: "Start the climb at midnight.", SI: "මධ්‍යම රාත්‍රියේදී නැගීම ආරම්භ කරන්න." }], location: "Ratnapura" },
  { id: "nuwara-eliya", name: { EN: "Nuwara Eliya Town", SI: "නුවරඑළිය නගරය" }, category: "mountains", image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "Known as 'Little England' for its colonial architecture.", SI: "යටත් විජිත ගෘහ නිර්මාණ ශිල්පය නිසා 'පුංචි එංගලන්තය' ලෙස හැඳින්වේ." }, shortStory: { EN: "Tea estates and misty valleys.", SI: "තේ වතු සහ මීදුමෙන් වැසුණු මිටියාවත්." }, bestTime: { EN: "April to May", SI: "අප්‍රේල් සිට මැයි දක්වා" }, tips: [{ EN: "Wear warm clothing even in daytime.", SI: "දිවා කාලයේ පවා උණුසුම් ඇඳුම් අඳින්න." }], location: "Nuwara Eliya" },
  { id: "bentota", name: { EN: "Bentota River & Beach", SI: "බෙන්තොට" }, category: "beach", image: "https://images.unsplash.com/photo-1558446791-ac5fec3caddf?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A water sports hub where the river meets the sea.", SI: "ගඟ සහ මුහුද හමුවන ජල ක්‍රීඩා සඳහා ප්‍රසිද්ධ ස්ථානයකි." }, shortStory: { EN: "Lanka's golden watersports playground.", SI: "ලංකාවේ රන්වන් ජල ක්‍රීඩා පාරාදීසය." }, bestTime: { EN: "October to April", SI: "ඔක්තෝබර් සිට අප්‍රේල් දක්වා" }, tips: [{ EN: "Try the river safari for bird watching.", SI: "කුරුල්ලන් නැරඹීමට ගංගා සවාරියක් යන්න." }], location: "Galle" },
  { id: "hikkaduwa", name: { EN: "Hikkaduwa Marine Park", SI: "හික්කඩුව වෙරළ" }, category: "beach", image: "https://images.unsplash.com/photo-1544921603-91185f0962b1?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A vibrant beach town famous for corals and nightlife.", SI: "කොරල්පර සහ විචිත්‍රවත් රාත්‍රී ජීවිතය සඳහා ප්‍රසිද්ධ වෙරළබඩ නගරයකි." }, shortStory: { EN: "The lively pulse of the Southern coast.", SI: "දකුණු වෙරළ තීරයේ ජීවමාන රිද්මය." }, bestTime: { EN: "November to April", SI: "නොවැම්බර් සිට අප්‍රේල් දක්වා" }, tips: [{ EN: "Take a glass-bottom boat to see corals.", SI: "කොරල් නැරඹීමට විනිවිද පෙනෙන බෝට්ටුවක් භාවිතා කරන්න." }], location: "Galle" },
  { id: "pasikudah", name: { EN: "Pasikudah Bay", SI: "පාසිකුඩා බොක්ක" }, category: "beach", image: "https://images.unsplash.com/photo-1544921603-91185f0962b1?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "Known for having one of the longest shallow reefs.", SI: "ලොව දිගම නොගැඹුරු වෙරළ තීරයක් සහිත ස්ථානයකි." }, shortStory: { EN: "Walking deep into the turquoise calm.", SI: "නිල්වන් සාගරය මැදින් ඇවිද යන්න." }, bestTime: { EN: "May to September", SI: "මැයි සිට සැප්තැම්බර් දක්වා" }, tips: [{ EN: "Perfect for family swimming.", SI: "පවුලේ සැමට පීනීමට ඉතා සුදුසුයි." }], location: "Batticaloa" },
  { id: "minneriya", name: { EN: "Minneriya Gathering", SI: "මින්නේරිය ජාතික උද්‍යානය" }, category: "wildlife", image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "Famous for 'The Gathering' of hundreds of elephants.", SI: "අලි ඇතුන් සිය ගණනක් එක්වන 'The Gathering' උත්සවය සඳහා ප්‍රසිද්ධය." }, shortStory: { EN: "The largest elephant assembly in Asia.", SI: "ආසියාවේ විශාලතම අලි එකතුව." }, bestTime: { EN: "July to September", SI: "ජූලි සිට සැප්තැම්බර් දක්වා" }, tips: [{ EN: "Visit during the dry season for more elephants.", SI: "වැඩිපුර අලි බැලීමට වියළි කාලයේදී යන්න." }], location: "Polonnaruwa" },
  { id: "wilpattu", name: { EN: "Wilpattu Lakes", SI: "විල්පත්තුව ජාතික උද්‍යානය" }, category: "wildlife", image: "https://images.unsplash.com/photo-1590766940554-634a7ed41450?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "Defined by many natural lakes or 'Villus'.", SI: "ස්වභාවික විල් හෙවත් 'විල්ලු' රැසකින් සමන්විත උද්‍යානයකි." }, shortStory: { EN: "The land of lakes and leopards.", SI: "විල් සහ දිවියන්ගේ දේශය." }, bestTime: { EN: "February to October", SI: "පෙබරවාරි සිට ඔක්තෝබර් දක්වා" }, tips: [{ EN: "Full day safari is recommended.", SI: "සම්පූර්ණ දින සවාරියක් නිර්දේශ කෙරේ." }], location: "Anuradhapura" },
  { id: "yapahuwa", name: { EN: "Yapahuwa Rock Fortress", SI: "යාපහුව බලකොටුව" }, category: "ancient", image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "The 13th-century capital, featuring a monumental staircase.", SI: "පෞරාණික පඩිපෙළකින් සමන්විත 13 වන සියවසේ රාජධානියයි." }, shortStory: { EN: "The stone climb to a lost kingdom.", SI: "නැතිවූ රාජධානියකට ගල් පඩිපෙළ ඔස්සේ." }, bestTime: { EN: "Year-round", SI: "වසර පුරා" }, tips: [{ EN: "Look for the Chinese-influenced carvings.", SI: "චීන ගෘහ නිර්මාණ ලක්ෂණ සහිත කැටයම් සොයන්න." }], location: "Kurunegala" },
  { id: "ritigala", name: { EN: "Ritigala Monastery", SI: "රිටිගල ආරණ්‍යය" }, category: "ancient", image: "https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A mist-shrouded ancient Buddhist monastery on a peak.", SI: "කඳු මුදුනක පිහිටි මීදුමෙන් වැසුණු පුරාණ බෞද්ධ ආරණ්‍යයකි." }, shortStory: { EN: "Whispers of monks in a sacred forest.", SI: "පූජනීය වනාන්තරයක භික්ෂූන්ගේ හඬ." }, bestTime: { EN: "June to August", SI: "ජූනි සිට අගෝස්තු දක්වා" }, tips: [{ EN: "Carry water as it is a remote trek.", SI: "දුෂ්කර මාවතක් බැවින් ජලය රැගෙන යන්න." }], location: "Anuradhapura" },
  { id: "mihintale", name: { EN: "Mihintale Peak", SI: "මිහින්තලය" }, category: "ancient", image: "https://images.unsplash.com/photo-1578503117502-3162799f9392?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "Where Buddhism was first introduced to Sri Lanka.", SI: "ශ්‍රී ලංකාවට බුදුදහම ප්‍රථමයෙන් දායාද වූ පින්බිමයි." }, shortStory: { EN: "The cradle of a new civilization.", SI: "නව ශිෂ්ටාචාරයක උපත." }, bestTime: { EN: "June (Poson Poya)", SI: "ජූනි (පොසොන් පෝය)" }, tips: [{ EN: "Visit at sunrise for a peaceful climb.", SI: "සන්සුන් තරණයකට හිරු උදාවේදී යන්න." }], location: "Anuradhapura" },
  { id: "trinco-koneswaram", name: { EN: "Koneswaram Temple", SI: "කෝණේශ්වරම් කෝවිල" }, category: "ancient", image: "https://images.unsplash.com/photo-1700315303907-5b222bb8bb47?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A classical Hindu temple overlooking the harbor.", SI: "ත්‍රිකුණාමල වරායට ඉහළින් පිහිටි පෞරාණික හින්දු දේවාලයකි." }, shortStory: { EN: "Faith perched upon the cliff's edge.", SI: "ප්‍රපාතය කෙළවර පිහිටි අචල භක්තිය." }, bestTime: { EN: "Year-round", SI: "වසර පුරා" }, tips: [{ EN: "View the 'Lover's Leap' cliff nearby.", SI: "අසල ඇති 'Lover's Leap' ප්‍රපාතය නරඹන්න." }], location: "Trincomalee" },
  { id: "jaffna-library", name: { EN: "Jaffna Library", SI: "යාපනය පුස්තකාලය" }, category: "ancient", image: "https://images.unsplash.com/photo-1541913007727-4663f21d9620?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A symbol of cultural resilience and northern knowledge.", SI: "සංස්කෘතික ඔරොත්තු දීමේ හැකියාව සහ උතුරේ දැනුමේ සංකේතයකි." }, shortStory: { EN: "The white beacon of northern learning.", SI: "උතුරේ දැනුමේ රන්වන් ලාම්පුව." }, bestTime: { EN: "January to September", SI: "ජනවාරි සිට සැප්තැම්බර් දක්වා" }, tips: [{ EN: "Respect the quiet study areas.", SI: "නිශ්ශබ්දතාවය සුරකින්න." }], location: "Jaffna" },
  { id: "knuckles-range", name: { EN: "Knuckles Forest", SI: "නකල්ස් රක්ෂිතය" }, category: "mountains", image: "https://images.unsplash.com/photo-1563297054-94676106c59b?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A biodiversity hotspot named for its knuckle-like shape.", SI: "මිටි කරන ලද ඇඟිලිවල හැඩය සහිත ජෛව විවිධත්ව කලාපයකි." }, shortStory: { EN: "The misty backbone of the island.", SI: "දිවයිනේ මීදුමෙන් වැසුණු කොඳු නාරටිය." }, bestTime: { EN: "December to February", SI: "දෙසැම්බර් සිට පෙබරවාරි දක්වා" }, tips: [{ EN: "Hire a local guide for treks.", SI: "සංචාර සඳහා ප්‍රදේශයේ මගපෙන්වන්නෙකු ලබා ගන්න." }], location: "Kandy" },
  { id: "haputale", name: { EN: "Haputale Gap", SI: "හපුතලේ" }, category: "mountains", image: "https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "Breathtaking views of the southern plains of Sri Lanka.", SI: "ශ්‍රී ලංකාවේ දකුණු තැන්න නිරීක්ෂණය කළ හැකි විස්මිත ස්ථානයකි." }, shortStory: { EN: "Where the mountains drop into infinity.", SI: "කඳු නිම්නය අවසන් වන තැන." }, bestTime: { EN: "January to April", SI: "ජනවාරි සිට අප්‍රේල් දක්වා" }, tips: [{ EN: "Visit Lipton's Seat for tea and views.", SI: "ලිප්ටන් සීට් වෙත ගොස් තේ රස බලන්න." }], location: "Badulla" },
  { id: "belihuloya", name: { EN: "Belihuloya River", SI: "බෙලිහුල්ඔය" }, category: "mountains", image: "https://images.unsplash.com/photo-1514483127413-f72f273478c3?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A scenic village where three environmental zones meet.", SI: "පාරිසරික කලාප තුනක් හමුවන අලංකාර ගම්මානයකි." }, shortStory: { EN: "Crystal clear streams and mountain air.", SI: "පිරිසිදු ජල දහරා සහ කඳුකර සුළඟ." }, bestTime: { EN: "Year-round", SI: "වසර පුරා" }, tips: [{ EN: "Visit Pahanthudawa waterfall nearby.", SI: "අසල ඇති පහන්තුඩාව දිය ඇල්ල නරඹන්න." }], location: "Ratnapura" },
  { id: "buduruwagala", name: { EN: "Buduruwagala Statues", SI: "බුදුරුවගල" }, category: "ancient", image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A massive rock housing seven ancient Mahayana statues.", SI: "මහායාන පිළිම වහන්සේලා හත්නමක් සහිත දැවැන්ත ගල් පර්වතයකි." }, shortStory: { EN: "Giant stone deities in the wild.", SI: "වනයේ මැද පිහිටි දැවැන්ත ගල් පිළිම." }, bestTime: { EN: "July to September", SI: "ජූලි සිට සැප්තැම්බර් දක්වා" }, tips: [{ EN: "Visit early morning for soft light.", SI: "උදෑසන කාලයේදී නැරඹීමට යන්න." }], location: "Monaragala" },
  { id: "aukana", name: { EN: "Aukana Buddha Statue", SI: "අවුකන බුදු පිළිමය" }, category: "ancient", image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A standing Buddha statue carved from a single granite rock.", SI: "තනි කළුගල් පර්වතයකින් නිමවා ඇති අලංකාර බුදු පිළිමයකි." }, shortStory: { EN: "Stone perfection of the 5th century.", SI: "5 වන සියවසේ ගල් කැටයම් කලාවේ විශිෂ්ටත්වය." }, bestTime: { EN: "Year-round", SI: "වසර පුරා" }, tips: [{ EN: "Observe the detail of the robe carvings.", SI: "සිවුරේ කැටයම් පිළිබඳ විමසිලිමත් වන්න." }], location: "Anuradhapura" },
  { id: "kumana", name: { EN: "Kumana Bird Reserve", SI: "කුමන ජාතික උද්‍යානය" }, category: "wildlife", image: "https://images.unsplash.com/photo-1590766940554-634a7ed41450?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "Sri Lanka's premier destination for bird watchers.", SI: "ශ්‍රී ලංකාවේ පක්ෂීන් නැරඹීම සඳහා ඇති හොඳම ස්ථානයයි." }, shortStory: { EN: "The sky's orchestra in the wetlands.", SI: "තෙත් බිම්වල සැරිසරන ගුවනේ සංගීතය." }, bestTime: { EN: "April to July", SI: "අප්‍රේල් සිට ජූලි දක්වා" }, tips: [{ EN: "Bring binoculars for bird identification.", SI: "පක්ෂීන් හඳුනා ගැනීමට දුරදක්න රැගෙන එන්න." }], location: "Ampara" },
  { id: "tangalle", name: { EN: "Tangalle Silent Beach", SI: "තංගල්ල වෙරළ" }, category: "beach", image: "https://images.unsplash.com/photo-1544921603-91185f0962b1?auto=format&fit=crop&w=1200&q=80", gallery: [], history: { EN: "A secluded coastal town known for its golden sand.", SI: "රන්වන් වැලි සහිත නිස්කලංක වෙරළබඩ නගරයකි." }, shortStory: { EN: "Silent shores of the deep south.", SI: "දකුණු කෙළවරේ නිහඬ වෙරළ තීරය." }, bestTime: { EN: "December to March", SI: "දෙසැම්බර් සිට මාර්තු දක්වා" }, tips: [{ EN: "Check out the Rekawa turtle hatchery.", SI: "රෙකව කැස්බෑ මධ්‍යස්ථානය නරඹන්න." }], location: "Hambantota" }
];

export const HIKING_DATA: HikingSpot[] = [
  { id: "h1", name: { EN: "Adam's Peak (Sri Pada)", SI: "ශ්‍රී පාදය" }, location: { EN: "Ratnapura", SI: "රත්නපුර" }, difficulty: "Hard", duration: { EN: "5-7 Hours", SI: "පැය 5-7" }, description: { EN: "A sacred mountain known for the 'Sri Pada' footprint at the summit.", SI: "මුදුනේ සිරිපතුල පිහිටි පූජනීය කන්දකි." }, image: "https://images.unsplash.com/photo-1705730312722-095ca8123d48?auto=format&fit=crop&w=800&q=80", elevation: "2,243m" },
  { id: "h2", name: { EN: "Ella Rock", SI: "ඇල්ල රොක්" }, location: { EN: "Ella", SI: "ඇල්ල" }, difficulty: "Moderate", duration: { EN: "3-4 Hours", SI: "පැය 3-4" }, description: { EN: "Panoramic views of the Ella Gap and tea estates.", SI: "ඇල්ල දුර්ගයේ අලංකාර දර්ශනයක් දැකගත හැක." }, image: "https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=800&q=80", elevation: "1,141m" },
  { id: "h3", name: { EN: "Wangedigala", SI: "වන්ගෙඩිගල" }, location: { EN: "Belihuloya", SI: "බෙලිහුල්ඔය" }, difficulty: "Challenging", duration: { EN: "4-5 Hours", SI: "පැය 4-5" }, description: { EN: "A sharp peak offering vertical views of the Samanalawewa reservoir.", SI: "සමනලවැව ජලාශයේ දර්ශන සහිත උස් කඳු මුදුනකි." }, image: "https://images.unsplash.com/photo-1563297054-94676106c59b?auto=format&fit=crop&w=800&q=80", elevation: "1,400m" }
];

export const FESTIVALS_DATA: Festival[] = [
  { id: "fest-1", name: { EN: "Vesak Festival", SI: "වෙසක් උත්සවය" }, date: { EN: "May (Full Moon)", SI: "මැයි (පුර පසළොස්වක)" }, description: { EN: "Commemorating the birth, enlightenment, and passing of Lord Buddha.", SI: "බුදුරජාණන් වහන්සේගේ තෙමඟුල සැමරීම." }, image: "https://images.unsplash.com/photo-1621393614326-2f9ed389ce02?auto=format&fit=crop&w=1200&q=80", significance: { EN: "Lights and lanterns across the island.", SI: "දිවයින පුරා පහන් සහ තොරණින් සැරසීම." } }
];

export const PHRASEBOOK_DATA: Phrase[] = [
  { id: "p1", english: "Hello / Ayubowan", sinhala: "ආයුබෝවන්", transliteration: "Ayubowan", category: "greeting" },
  { id: "p2", english: "Thank you", sinhala: "ස්තූතියි", transliteration: "Stutiyi", category: "greeting" }
];

export const FOODS_DATA: Food[] = [
  {
    id: "f1",
    name: { EN: "Rice and Curry", SI: "බත් සහ වෑංජන" },
    description: { EN: "The staple meal, featuring multiple curries.", SI: "ප්‍රධාන දේශීය ආහාර වේල." },
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80",
    spiciness: 4,
    ingredients: [{ EN: "Rice", SI: "බත්" }, { EN: "Coconut", SI: "පොල්" }],
    tasteProfile: { EN: "Spicy", SI: "සැර" }
  }
];

export const MEDICINE_DATA: TraditionalMedicine[] = [
  { id: "herb-1", type: "herb", name: { EN: "Neem", SI: "කොහොඹ" }, description: { EN: "Antiseptic properties.", SI: "විෂබීජ නාශක ගුණ." }, image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80", benefits: { EN: "Skin health.", SI: "සමේ සෞඛ්‍යය." }, usage: { EN: "Paste.", SI: "ආලේපනයක් ලෙස." } }
];

export const TEA_DATA: TeaExperience[] = [
  { id: "tea1", name: { EN: "Ceylon Black Tea", SI: "කළු තේ" }, description: { EN: "World famous.", SI: "ලොව සුප්‍රසිද්ධයි." }, image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80", type: "variety", fact: { EN: "Pure quality.", SI: "උසස් තත්ත්වයේ." } }
];

export const TRAVEL_ESSENTIALS_DATA: TravelEssential[] = [
  { id: "e1", title: { EN: "Visa", SI: "වීසා" }, description: { EN: "Apply online.", SI: "සබැඳිව අයදුම් කරන්න." }, icon: "ShieldCheck", tips: [{ EN: "Check passport validity.", SI: "වලංගු කාලය පරීක්ෂා කරන්න." }] }
];

export const CATEGORIES_DATA = [
  { id: 'hiking', icon: 'Mountain', title: { EN: 'Heritage Hiking', SI: 'උරුම කඳු තරණය' }, description: { EN: 'Scale the cloud forests where kings once meditated.', SI: 'රජවරුන් භාවනා කළ මීදුමෙන් වැසුණු කඳු මුදුන් කරා.' } },
  { id: 'foods', icon: 'Utensils', title: { EN: 'Food Heritage', SI: 'ආහාර උරුමය' }, description: { EN: 'Taste the ancient spices of an island civilization.', SI: 'දිවයිනේ පැරණි කුළුබඩු රසයෙන් පිරි ආහාර සංස්කෘතිය.' } },
  { id: 'music', icon: 'Music', title: { EN: 'Ancient Music', SI: 'පැරණි සංගීතය' }, description: { EN: 'Listen to the rhythmic heartbeat of a nation.', SI: 'ජාතියක හදගැස්ම බඳු වූ පාරම්පරික රිද්මයන්.' } },
  { id: 'medicine', icon: 'Activity', title: { EN: 'Hela Wedakama', SI: 'හෙළ වෙදකම' }, description: { EN: '5000 years of indigenous neural healing.', SI: 'වසර 5000 ක් පැරණි දේශීය සුව කිරීමේ ප්‍රඥාව.' } },
  { id: 'tea', icon: 'Sprout', title: { EN: 'Tea Culture', SI: 'තේ සංස්කෘතිය' }, description: { EN: 'Discover the world of Ceylon tea.', SI: 'ලංකා තේ සංස්කෘතිය ගවේෂණය කරන්න.' } },
  { id: 'phrases', icon: 'MessageSquare', title: { EN: 'Local Language', SI: 'දේශීය භාෂාව' }, description: { EN: 'Learn essential Sinhala phrases.', SI: 'මූලික සිංහල වාක්‍ය ඛණ්ඩ ඉගෙන ගන්න.' } },
  { id: 'essentials', icon: 'Backpack', title: { EN: 'Travel Guide', SI: 'සංචාරක උපදෙස්' }, description: { EN: 'Practical tips for your journey.', SI: 'ඔබේ ගමනට ප්‍රායෝගික උපදෙස්.' } },
  { id: 'festivals', icon: 'PartyPopper', title: { EN: 'Festivals', SI: 'සංස්කෘතික උත්සව' }, description: { EN: 'Join the celebrations of the island.', SI: 'දිවයිනේ උත්සව සැමරුම් සමඟ එක්වන්න.' } }
];

export const HERITAGE_MUSIC_DATA: HeritageMusic[] = [
  { id: 'm1', type: 'instrument', name: { EN: 'Geta Beraya', SI: 'ගැට බෙරය' }, description: { EN: 'The traditional drum used in Kandyan dancing.', SI: 'උඩරට නැටුම් සඳහා භාවිතා කරන පාරම්පරික බෙරය.' }, image: 'https://images.unsplash.com/photo-1665849050332-8d5d7e59afb6?auto=format&fit=crop&w=800&q=80', origin: { EN: 'Hill Country', SI: 'කඳුකරය' }, significance: { EN: 'Essential for spiritual ceremonies.', SI: 'ආත්මික චාරිත්‍ර සඳහා අත්‍යවශ්‍ය වේ.' } }
];
